services:
  telebot:
    image: ghcr.io/tiephoangdev/vps-telebot:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /root:/root:ro
    env_file:
      - .env
